import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const scholarships = [
  {
    name: "Gates Millennium Scholarship",
    amount: 5000,
    amountMax: 20000,
    deadline: new Date("2026-01-15"),
    applicationUrl: "https://www.gmsp.org/",
    source: "Gates Foundation",
    requiredDocs: JSON.stringify(["GPA verification", "Nomination letter", "Personal statement"]),
    essayPrompts: JSON.stringify(["Describe a community need and how you plan to address it."]),
    educationLevel: JSON.stringify(["HS_SENIOR", "UNDERGRAD_YEAR_1", "UNDERGRAD_YEAR_2", "UNDERGRAD_YEAR_3", "UNDERGRAD_YEAR_4"]),
    citizenshipTypes: JSON.stringify(["US_CITIZEN", "PERMANENT_RESIDENT"]),
    gpaMin: "3.3",
    demographics: JSON.stringify(["FIRST_GENERATION", "LOW_INCOME"]),
    incomeBrackets: JSON.stringify(["UNDER_15000", "15000_30000", "30000_50000"]),
    raceEthnicity: JSON.stringify(["African American", "American Indian/Alaska Native", "Asian American", "Hispanic/Latino", "Pacific Islander"]),
    canonicalUrl: "https://www.gmsp.org/",
    nameHash: "gates-millennium",
    eligibilityFingerprint: "minority-poc-lowincome-3.3gpa",
  },
  {
    name: "Coca-Cola Scholars Program",
    amount: 20000,
    amountMax: 20000,
    deadline: new Date("2026-10-31"),
    applicationUrl: "https://www.coca-colascholars.org/",
    source: "Coca-Cola",
    requiredDocs: JSON.stringify(["Transcripts", "Two recommendation letters", "Essay"]),
    essayPrompts: JSON.stringify(["Describe your leadership impact and future goals."]),
    educationLevel: JSON.stringify(["HS_SENIOR"]),
    citizenshipTypes: JSON.stringify(["US_CITIZEN", "PERMANENT_RESIDENT"]),
    gpaMin: "3.0",
    canonicalUrl: "https://www.coca-colascholars.org/",
    nameHash: "coca-cola-scholars",
    eligibilityFingerprint: "hs-senior-merit",
  },
  {
    name: "Ron Brown Scholar Program",
    amount: 10000,
    amountMax: 40000,
    deadline: new Date("2026-01-01"),
    applicationUrl: "https://ronbrown.org/",
    source: "Ron Brown Scholar Program",
    requiredDocs: JSON.stringify(["Transcripts", "Essay", "Financial info", "Recommendation letters"]),
    essayPrompts: JSON.stringify(["Discuss a time you demonstrated leadership.", "Describe your career aspirations."]),
    educationLevel: JSON.stringify(["HS_SENIOR"]),
    citizenshipTypes: JSON.stringify(["US_CITIZEN"]),
    demographics: JSON.stringify(["AFRICAN_AMERICAN"]),
    gpaMin: "3.0",
    incomeBrackets: JSON.stringify(["UNDER_15000", "15000_30000", "30000_50000", "50000_75000"]),
    canonicalUrl: "https://ronbrown.org/",
    nameHash: "ron-brown-scholar",
    eligibilityFingerprint: "africanamerican-need",
  },
  {
    name: "Jack Kent Cooke Foundation College Scholarship",
    amount: 40000,
    amountMax: 40000,
    deadline: new Date("2026-01-07"),
    applicationUrl: "https://www.jkcf.org/",
    source: "Jack Kent Cooke Foundation",
    requiredDocs: JSON.stringify(["Transcripts", "Recommendations", "Essay", "Financial documents"]),
    essayPrompts: JSON.stringify(["Describe your educational journey and challenges overcome."]),
    educationLevel: JSON.stringify(["HS_SENIOR"]),
    citizenshipTypes: JSON.stringify(["US_CITIZEN", "PERMANENT_RESIDENT"]),
    gpaMin: "3.0",
    incomeBrackets: JSON.stringify(["UNDER_15000", "15000_30000", "30000_50000"]),
    demographics: JSON.stringify(["FIRST_GENERATION", "LOW_INCOME"]),
    canonicalUrl: "https://www.jkcf.org/our-scholarships/",
    nameHash: "jack-kent-cooke",
    eligibilityFingerprint: "highachieving-lowincome",
  },
  {
    name: "Dell Scholars Program",
    amount: 20000,
    amountMax: 20000,
    deadline: new Date("2026-01-12"),
    applicationUrl: "https://www.dellscholars.org/",
    source: "Michael & Susan Dell Foundation",
    requiredDocs: JSON.stringify(["Transcripts", "Essay", "FAFSA", "Recommendation letter"]),
    essayPrompts: JSON.stringify(["Describe how you overcame an obstacle in your life."]),
    educationLevel: JSON.stringify(["HS_SENIOR"]),
    citizenshipTypes: JSON.stringify(["US_CITIZEN", "PERMANENT_RESIDENT"]),
    gpaMin: "2.4",
    incomeBrackets: JSON.stringify(["UNDER_15000", "15000_30000", "30000_50000", "50000_75000"]),
    demographics: JSON.stringify(["LOW_INCOME"]),
    canonicalUrl: "https://www.dellscholars.org/",
    nameHash: "dell-scholars",
    eligibilityFingerprint: "lowincome-committed",
  },
  {
    name: "Horatio Alger Association Scholarship",
    amount: 10000,
    amountMax: 40000,
    deadline: new Date("2026-03-31"),
    applicationUrl: "https://horatioalger.org/",
    source: "Horatio Alger Association",
    requiredDocs: JSON.stringify(["Transcripts", "Essay", "Financial info"]),
    essayPrompts: JSON.stringify(["Describe overcoming adversity and pursuing goals."]),
    educationLevel: JSON.stringify(["HS_SENIOR", "UNDERGRAD_YEAR_1"]),
    citizenshipTypes: JSON.stringify(["US_CITIZEN", "PERMANENT_RESIDENT"]),
    gpaMin: "2.0",
    incomeBrackets: JSON.stringify(["UNDER_15000", "15000_30000", "30000_50000"]),
    demographics: JSON.stringify(["LOW_INCOME", "FIRST_GENERATION"]),
    canonicalUrl: "https://horatioalger.org/scholarships/",
    nameHash: "horatio-alger",
    eligibilityFingerprint: "adversity-overcome",
  },
  {
    name: "McDonald's All-American Scholarship",
    amount: 10000,
    amountMax: 10000,
    deadline: new Date("2026-02-28"),
    applicationUrl: "https://www.mcdonaldsallamerican.com/",
    source: "McDonald's",
    requiredDocs: JSON.stringify(["Athletic profile", "Coach recommendation", "Transcripts"]),
    essayPrompts: JSON.stringify(["Describe your athletic and academic goals."]),
    educationLevel: JSON.stringify(["HS_SENIOR"]),
    citizenshipTypes: JSON.stringify(["US_CITIZEN"]),
    gpaMin: "2.5",
    canonicalUrl: "https://www.mcdonaldsallamerican.com/",
    nameHash: "mcdonalds-all-american",
    eligibilityFingerprint: "athlete-hs-senior",
  },
  {
    name: "USDA/1890 National Scholarship",
    amount: 10000,
    amountMax: 40000,
    deadline: new Date("2026-01-31"),
    applicationUrl: "https://www.usda.gov/",
    source: "USDA",
    requiredDocs: JSON.stringify(["Transcripts", "Essay", "Recommendation letters", "FAFSA"]),
    essayPrompts: JSON.stringify(["Describe your interest in agriculture and food sciences."]),
    educationLevel: JSON.stringify(["HS_SENIOR", "UNDERGRAD_YEAR_1"]),
    citizenshipTypes: JSON.stringify(["US_CITIZEN"]),
    majors: JSON.stringify(["Agriculture", "Food Science", "Animal Science", "Agri-Business", "Biological Sciences", "Environmental Science"]),
    canonicalUrl: "https://www.usda.gov/youth/scholarships",
    nameHash: "usda-1890-scholarship",
    eligibilityFingerprint: "usda-1890",
  },
  {
    name: "AAF Scholarship",
    amount: 5000,
    amountMax: 10000,
    deadline: new Date("2026-03-01"),
    applicationUrl: "https://www.aaf.org/",
    source: "AAF",
    requiredDocs: JSON.stringify(["Portfolio", "Transcripts", "Essay"]),
    essayPrompts: JSON.stringify(["Describe your career goals in advertising."]),
    educationLevel: JSON.stringify(["UNDERGRAD_YEAR_1", "UNDERGRAD_YEAR_2", "UNDERGRAD_YEAR_3", "UNDERGRAD_YEAR_4"]),
    majors: JSON.stringify(["Advertising", "Marketing", "Communications", "Graphic Design", "Journalism"]),
    gpaMin: "3.0",
    canonicalUrl: "https://www.aaf.org/awards/scholarships",
    nameHash: "aaf-scholarship",
    eligibilityFingerprint: "advertising-communications",
  },
  {
    name: "AMS Minority Scholarship",
    amount: 6000,
    amountMax: 6000,
    deadline: new Date("2026-02-28"),
    applicationUrl: "https://www.ametsoc.org/",
    source: "AMS",
    requiredDocs: JSON.stringify(["Transcripts", "Essay", "Recommendation letters"]),
    essayPrompts: JSON.stringify(["Describe your interest in atmospheric sciences."]),
    educationLevel: JSON.stringify(["UNDERGRAD_YEAR_1", "UNDERGRAD_YEAR_2", "UNDERGRAD_YEAR_3", "UNDERGRAD_YEAR_4"]),
    citizenshipTypes: JSON.stringify(["US_CITIZEN", "PERMANENT_RESIDENT"]),
    demographics: JSON.stringify(["AFRICAN_AMERICAN", "Hispanic/Latino", "American Indian"]),
    majors: JSON.stringify(["Meteorology", "Atmospheric Science", "Oceanography", "Environmental Science"]),
    gpaMin: "3.0",
    canonicalUrl: "https://www.ametsoc.org/ams/index.cfm/awards-and-honors/ams-minority-scholarships/",
    nameHash: "ams-minority-scholarship",
    eligibilityFingerprint: "poc-stem-meteorology",
  },
  {
    name: "NIH Undergraduate Scholarship Program",
    amount: 20000,
    amountMax: 80000,
    deadline: new Date("2026-03-15"),
    applicationUrl: "https://www.nih.gov/",
    source: "NIH",
    requiredDocs: JSON.stringify(["FAFSA", "Transcripts", "Essay", "Recommendations"]),
    essayPrompts: JSON.stringify(["Describe your commitment to health research careers."]),
    educationLevel: JSON.stringify(["UNDERGRAD_YEAR_1", "UNDERGRAD_YEAR_2", "UNDERGRAD_YEAR_3", "UNDERGRAD_YEAR_4"]),
    citizenshipTypes: JSON.stringify(["US_CITIZEN"]),
    incomeBrackets: JSON.stringify(["UNDER_15000", "15000_30000", "30000_50000"]),
    demographics: JSON.stringify(["DISABILITY", "DISPLACED_WORKER"]),
    majors: JSON.stringify(["Biology", "Chemistry", "Physics", "Public Health", "Biomedical Engineering", "Neuroscience"]),
    gpaMin: "3.0",
    canonicalUrl: "https://www.nigms.nih.gov/research-training/research-training-paths/ugsp",
    nameHash: "nih-undergrad-scholarship",
    eligibilityFingerprint: "health-research-need",
  },
  {
    name: "Blck VC Scholarship",
    amount: 10000,
    amountMax: 10000,
    deadline: new Date("2026-04-01"),
    applicationUrl: "https://blackvc.org/",
    source: "Blck VC",
    requiredDocs: JSON.stringify(["Resume", "Essay", "Video intro"]),
    essayPrompts: JSON.stringify(["Describe your interest in venture capital and tech."]),
    educationLevel: JSON.stringify(["UNDERGRAD_YEAR_1", "UNDERGRAD_YEAR_2", "UNDERGRAD_YEAR_3", "UNDERGRAD_YEAR_4", "GRAD_MASTERS"]),
    demographics: JSON.stringify(["AFRICAN_AMERICAN"]),
    majors: JSON.stringify(["Computer Science", "Business", "Economics", "Finance", "Engineering"]),
    canonicalUrl: "https://www.blackvc.org/scholarship",
    nameHash: "blck-vc-scholarship",
    eligibilityFingerprint: "africanamerican-tech-business",
  },
  {
    name: "CIA Undergraduate Scholarship Program",
    amount: 18000,
    amountMax: 72000,
    deadline: new Date("2026-06-30"),
    applicationUrl: "https://www.cia.gov/",
    source: "CIA",
    requiredDocs: JSON.stringify(["Background investigation", "Transcripts", "Essay"]),
    essayPrompts: JSON.stringify(["Describe your interest in serving the nation."]),
    educationLevel: JSON.stringify(["UNDERGRAD_YEAR_1", "UNDERGRAD_YEAR_2", "UNDERGRAD_YEAR_3", "UNDERGRAD_YEAR_4"]),
    citizenshipTypes: JSON.stringify(["US_CITIZEN"]),
    majors: JSON.stringify(["Computer Science", "Engineering", "International Relations", "Political Science", "Foreign Languages", "Chemistry", "Physics"]),
    gpaMin: "3.0",
    canonicalUrl: "https://www.cia.gov/careers/student-opportunities/undergraduate-scholarship-program/",
    nameHash: "cia-undergrad-scholarship",
    eligibilityFingerprint: "cia-national-service",
  },
  {
    name: "Marshall Scholarship",
    amount: 80000,
    amountMax: 80000,
    deadline: new Date("2026-09-01"),
    applicationUrl: "https://www.marshallscholarship.org/",
    source: "UK Government",
    requiredDocs: JSON.stringify(["Transcripts", "Essays (3)", "References", "Nomination from campus"]),
    essayPrompts: JSON.stringify(["Why do you want to study in the UK?", "Describe your academic and career goals."]),
    educationLevel: JSON.stringify(["UNDERGRAD_YEAR_4", "GRAD_MASTERS"]),
    citizenshipTypes: JSON.stringify(["US_CITIZEN"]),
    gpaMin: "3.7",
    majors: JSON.stringify(["All fields"]),
    canonicalUrl: "https://www.marshallscholarship.org/",
    nameHash: "marshall-scholarship",
    eligibilityFingerprint: "gates-uk-study",
  },
  {
    name: "Fulbright Student Program",
    amount: 0,
    amountMax: 0,
    deadline: new Date("2026-04-01"),
    applicationUrl: "https://us.fulbrightonline.org/",
    source: "US Department of State",
    requiredDocs: JSON.stringify(["Transcripts", "Essays", "References", "Language proficiency"]),
    essayPrompts: JSON.stringify(["Describe your project proposal and why you want to go."]),
    educationLevel: JSON.stringify(["UNDERGRAD_YEAR_4", "GRAD_MASTERS", "GRAD_PHD", "GRAD_PROFESSIONAL"]),
    citizenshipTypes: JSON.stringify(["US_CITIZEN"]),
    gpaMin: "3.0",
    canonicalUrl: "https://us.fulbrightonline.org/",
    nameHash: "fulbright-student",
    eligibilityFingerprint: "international-exchange",
  },
  {
    name: "NSF Graduate Research Fellowship",
    amount: 37000,
    amountMax: 148000,
    deadline: new Date("2025-10-20"),
    applicationUrl: "https://www.nsf.gov/",
    source: "NSF",
    requiredDocs: JSON.stringify(["Transcripts", "Research statement", "References (3)"]),
    essayPrompts: JSON.stringify(["Describe your research interests and career goals."]),
    educationLevel: JSON.stringify(["UNDERGRAD_YEAR_4", "GRAD_MASTERS", "GRAD_PHD"]),
    citizenshipTypes: JSON.stringify(["US_CITIZEN", "PERMANENT_RESIDENT"]),
    gpaMin: "3.0",
    majors: JSON.stringify(["STEM fields", "Social Sciences", "Education"]),
    canonicalUrl: "https://www.nsfgrfp.org/",
    nameHash: "nsf-grfp",
    eligibilityFingerprint: "stem-research",
  },
  {
    name: "P.E.O. Foundation STAR Scholarship",
    amount: 2500,
    amountMax: 2500,
    deadline: new Date("2026-01-15"),
    applicationUrl: "https://www.peointernational.org/",
    source: "P.E.O. Foundation",
    requiredDocs: JSON.stringify(["Transcripts", "Essay", "Financial info"]),
    essayPrompts: JSON.stringify(["Describe your educational goals and financial need."]),
    educationLevel: JSON.stringify(["HS_SENIOR"]),
    citizenshipTypes: JSON.stringify(["US_CITIZEN", "PERMANENT_RESIDENT"]),
    demographics: JSON.stringify(["FEMALE"]),
    gpaMin: "3.0",
    incomeBrackets: JSON.stringify(["UNDER_15000", "15000_30000", "30000_50000"]),
    canonicalUrl: "https://www.peointernational.org/our-causes/peace-pencil/scholarships",
    nameHash: "peo-star-scholarship",
    eligibilityFingerprint: "women-need",
  },
  {
    name: "NABA Scholarship",
    amount: 5000,
    amountMax: 15000,
    deadline: new Date("2026-02-28"),
    applicationUrl: "https://www.nabainc.org/",
    source: "NABA",
    requiredDocs: JSON.stringify(["Transcripts", "Resume", "Essay", "Recommendation letter"]),
    essayPrompts: JSON.stringify(["Describe your career goals in accounting/finance."]),
    educationLevel: JSON.stringify(["UNDERGRAD_YEAR_1", "UNDERGRAD_YEAR_2", "UNDERGRAD_YEAR_3", "UNDERGRAD_YEAR_4"]),
    demographics: JSON.stringify(["AFRICAN_AMERICAN"]),
    majors: JSON.stringify(["Accounting", "Finance", "Business Administration", "Economics"]),
    gpaMin: "3.0",
    canonicalUrl: "https://www.nabainc.org/scholarships",
    nameHash: "naba-scholarship",
    eligibilityFingerprint: "africanamerican-accounting",
  },
  {
    name: "Point Foundation Scholarship",
    amount: 10000,
    amountMax: 40000,
    deadline: new Date("2026-01-31"),
    applicationUrl: "https://pointfoundation.org/",
    source: "Point Foundation",
    requiredDocs: JSON.stringify(["Transcripts", "Essay", "Financial documents", "Recommendations"]),
    essayPrompts: JSON.stringify(["Describe your identity, leadership, and goals as an LGBTQ student."]),
    educationLevel: JSON.stringify(["HS_SENIOR", "UNDERGRAD_YEAR_1", "UNDERGRAD_YEAR_2", "UNDERGRAD_YEAR_3", "UNDERGRAD_YEAR_4", "GRAD_MASTERS"]),
    gpaMin: "2.5",
    canonicalUrl: "https://pointfoundation.org/apply/",
    nameHash: "point-foundation-scholarship",
    eligibilityFingerprint: "lgbtq-leader",
  },
  {
    name: "AIGA Scholarship",
    amount: 1000,
    amountMax: 50000,
    deadline: new Date("2026-05-31"),
    applicationUrl: "https://www.aigcs.org/",
    source: "AIGC",
    requiredDocs: JSON.stringify(["Tribal affiliation", "Transcripts", "Essay", "FAFSA"]),
    essayPrompts: JSON.stringify(["Describe your educational goals and tribal community involvement."]),
    educationLevel: JSON.stringify(["UNDERGRAD_YEAR_1", "UNDERGRAD_YEAR_2", "UNDERGRAD_YEAR_3", "UNDERGRAD_YEAR_4", "GRAD_MASTERS", "GRAD_PHD"]),
    demographics: JSON.stringify(["AMERICAN_INDIAN", "ALASKA_NATIVE"]),
    gpaMin: "2.0",
    canonicalUrl: "https://www.aigcs.org/scholarships",
    nameHash: "aiga-scholarship",
    eligibilityFingerprint: "nativeamerican-highered",
  },
  {
    name: "Hispanic Scholarship Fund Scholar Program",
    amount: 5000,
    amountMax: 20000,
    deadline: new Date("2026-03-15"),
    applicationUrl: "https://www.hsf.net/",
    source: "Hispanic Scholarship Fund",
    requiredDocs: JSON.stringify(["Transcripts", "Essay", "Tax return", "Recommendation letter"]),
    essayPrompts: JSON.stringify(["Describe your academic journey and commitment to the Hispanic community."]),
    educationLevel: JSON.stringify(["HS_SENIOR", "UNDERGRAD_YEAR_1", "UNDERGRAD_YEAR_2", "UNDERGRAD_YEAR_3", "UNDERGRAD_YEAR_4", "GRAD_MASTERS", "GRAD_PHD"]),
    citizenshipTypes: JSON.stringify(["US_CITIZEN", "PERMANENT_RESIDENT"]),
    ethnicity: JSON.stringify(["Hispanic", "Latino"]),
    gpaMin: "3.0",
    canonicalUrl: "https://www.hsf.net/scholarships",
    nameHash: "hsf-scholar",
    eligibilityFingerprint: "hispanic-latino",
  },
  {
    name: "APIA Scholarship",
    amount: 5000,
    amountMax: 20000,
    deadline: new Date("2026-01-15"),
    applicationUrl: "https://apiasf.org/",
    source: "APIA Scholar",
    requiredDocs: JSON.stringify(["Transcripts", "Essay", "Tax return", "Recommendation letter"]),
    essayPrompts: JSON.stringify(["Describe your heritage, community involvement, and goals."]),
    educationLevel: JSON.stringify(["HS_SENIOR", "UNDERGRAD_YEAR_1", "UNDERGRAD_YEAR_2", "UNDERGRAD_YEAR_3", "UNDERGRAD_YEAR_4"]),
    citizenshipTypes: JSON.stringify(["US_CITIZEN", "PERMANENT_RESIDENT"]),
    ethnicity: JSON.stringify(["Asian American", "Pacific Islander"]),
    incomeBrackets: JSON.stringify(["UNDER_15000", "15000_30000", "30000_50000", "50000_75000"]),
    gpaMin: "2.7",
    canonicalUrl: "https://apiasf.org/",
    nameHash: "apia-scholarship",
    eligibilityFingerprint: "asian-pacific-islander-need",
  },
  {
    name: "CHCI Scholarship",
    amount: 5000,
    amountMax: 25000,
    deadline: new Date("2026-03-31"),
    applicationUrl: "https://chci.org/",
    source: "CHCI",
    requiredDocs: JSON.stringify(["Transcripts", "Essay", "Tax return", "Recommendations"]),
    essayPrompts: JSON.stringify(["Describe your leadership and commitment to Hispanic community."]),
    educationLevel: JSON.stringify(["HS_SENIOR", "UNDERGRAD_YEAR_1", "UNDERGRAD_YEAR_2", "UNDERGRAD_YEAR_3", "UNDERGRAD_YEAR_4", "GRAD_MASTERS"]),
    citizenshipTypes: JSON.stringify(["US_CITIZEN", "PERMANENT_RESIDENT"]),
    ethnicity: JSON.stringify(["Hispanic", "Latino"]),
    gpaMin: "2.5",
    canonicalUrl: "https://chci.org/scholarships/",
    nameHash: "chci-scholarship",
    eligibilityFingerprint: "hispanic-leadership",
  },
  {
    name: "College Equity Scholarship",
    amount: 5000,
    amountMax: 15000,
    deadline: new Date("2026-02-15"),
    applicationUrl: "https://www.tcf.org/",
    source: "The Century Foundation",
    requiredDocs: JSON.stringify(["Transcripts", "Essay", "Community involvement"]),
    essayPrompts: JSON.stringify(["Describe barriers you have overcome in pursuing education."]),
    educationLevel: JSON.stringify(["UNDERGRAD_YEAR_1", "UNDERGRAD_YEAR_2", "UNDERGRAD_YEAR_3", "UNDERGRAD_YEAR_4"]),
    demographics: JSON.stringify(["AFRICAN_AMERICAN", "LOW_INCOME", "FIRST_GENERATION"]),
    gpaMin: "2.5",
    canonicalUrl: "https://tcf.org/content/about/college-equity-scholars/",
    nameHash: "college-equity-scholarship",
    eligibilityFingerprint: "equity-firstgen",
  },
  {
    name: "IEEE Telecommunications Engineering Scholarship",
    amount: 5000,
    amountMax: 15000,
    deadline: new Date("2026-03-01"),
    applicationUrl: "https://www.ieee.org/",
    source: "IEEE Foundation",
    requiredDocs: JSON.stringify(["Transcripts", "Essay", "Recommendation letter"]),
    essayPrompts: JSON.stringify(["Describe your interest in telecommunications engineering."]),
    educationLevel: JSON.stringify(["UNDERGRAD_YEAR_1", "UNDERGRAD_YEAR_2", "UNDERGRAD_YEAR_3", "UNDERGRAD_YEAR_4"]),
    majors: JSON.stringify(["Electrical Engineering", "Computer Engineering", "Telecommunications", "Computer Science"]),
    gpaMin: "3.0",
    canonicalUrl: "https://www.ieee.org/membership/student/scholarships.html",
    nameHash: "ieee-telecom-scholarship",
    eligibilityFingerprint: "engineering-telecom",
  },
  {
    name: "NSA Stokes Scholarship",
    amount: 30000,
    amountMax: 120000,
    deadline: new Date("2026-11-01"),
    applicationUrl: "https://www.nsa.gov/",
    source: "NSA",
    requiredDocs: JSON.stringify(["Transcripts", "Essay", "Background investigation waiver", "References"]),
    essayPrompts: JSON.stringify(["Describe your interest in national security and Cryptology."]),
    educationLevel: JSON.stringify(["HS_SENIOR", "UNDERGRAD_YEAR_1", "UNDERGRAD_YEAR_2", "UNDERGRAD_YEAR_3", "UNDERGRAD_YEAR_4"]),
    citizenshipTypes: JSON.stringify(["US_CITIZEN"]),
    majors: JSON.stringify(["Mathematics", "Computer Science", "Electrical Engineering", "Physics", "Foreign Languages", "Cryptology"]),
    gpaMin: "3.0",
    canonicalUrl: "https://www.nsa.gov/students-employees/cryptologic-scholars-program/",
    nameHash: "nsa-stokes-scholarship",
    eligibilityFingerprint: "nsa-cryptology-stem",
  },
  {
    name: "SMART Scholarship",
    amount: 25000,
    amountMax: 100000,
    deadline: new Date("2026-01-31"),
    applicationUrl: "https://www.smart.gov/",
    source: "DoD",
    requiredDocs: JSON.stringify(["Transcripts", "Essay", "References", "FAFSA"]),
    essayPrompts: JSON.stringify(["Describe your commitment to service and STEM study."]),
    educationLevel: JSON.stringify(["UNDERGRAD_YEAR_1", "UNDERGRAD_YEAR_2", "UNDERGRAD_YEAR_3", "UNDERGRAD_YEAR_4", "GRAD_MASTERS", "GRAD_PHD"]),
    citizenshipTypes: JSON.stringify(["US_CITIZEN"]),
    majors: JSON.stringify(["STEM fields"]),
    gpaMin: "3.0",
    canonicalUrl: "https://www.smart.gov/",
    nameHash: "smart-scholarship",
    eligibilityFingerprint: "dod-stem-service",
  },
  {
    name: "Buick Achievers Scholarship Program",
    amount: 25000,
    amountMax: 100000,
    deadline: new Date("2026-01-31"),
    applicationUrl: "https://www.buickachievers.com/",
    source: "GM Foundation",
    requiredDocs: JSON.stringify(["Transcripts", "Essay", "Financial info", "Recommendation letter"]),
    essayPrompts: JSON.stringify(["Describe your academic and career goals in automotive/engineering."]),
    educationLevel: JSON.stringify(["HS_SENIOR", "UNDERGRAD_YEAR_1", "UNDERGRAD_YEAR_2"]),
    citizenshipTypes: JSON.stringify(["US_CITIZEN", "PERMANENT_RESIDENT"]),
    majors: JSON.stringify(["Engineering", "Design", "Business", "Manufacturing", "Technology"]),
    gpaMin: "2.5",
    incomeBrackets: JSON.stringify(["UNDER_15000", "15000_30000", "30000_50000", "50000_75000"]),
    canonicalUrl: "https://www.buickachievers.com/",
    nameHash: "buick-achievers-scholarship",
    eligibilityFingerprint: "engineering-automotive",
  },
  {
    name: "NAWBO Scholarship",
    amount: 5000,
    amountMax: 15000,
    deadline: new Date("2026-03-01"),
    applicationUrl: "https://www.nawbo.org/",
    source: "NAWBO",
    requiredDocs: JSON.stringify(["Business plan", "Transcripts", "Essay", "Recommendation"]),
    essayPrompts: JSON.stringify(["Describe your entrepreneurial goals."]),
    educationLevel: JSON.stringify(["UNDERGRAD_YEAR_1", "UNDERGRAD_YEAR_2", "UNDERGRAD_YEAR_3", "UNDERGRAD_YEAR_4", "GRAD_MASTERS"]),
    demographics: JSON.stringify(["FEMALE"]),
    majors: JSON.stringify(["Business", "Entrepreneurship", "Marketing", "Finance"]),
    gpaMin: "3.0",
    canonicalUrl: "https://www.nawbo.org/scholarships",
    nameHash: "nawbo-scholarship",
    eligibilityFingerprint: "women-entrepreneurship",
  },
  {
    name: "Google Lime Scholarship",
    amount: 10000,
    amountMax: 20000,
    deadline: new Date("2026-03-15"),
    applicationUrl: "https://buildyourfuture.withgoogle.com/",
    source: "Google",
    requiredDocs: JSON.stringify(["Resume", "Transcripts", "Essay"]),
    essayPrompts: JSON.stringify(["Describe how you use technology to make a difference."]),
    educationLevel: JSON.stringify(["UNDERGRAD_YEAR_1", "UNDERGRAD_YEAR_2", "UNDERGRAD_YEAR_3", "UNDERGRAD_YEAR_4", "GRAD_MASTERS"]),
    demographics: JSON.stringify(["DISABILITY"]),
    majors: JSON.stringify(["Computer Science", "Engineering", "Technology", "Business"]),
    gpaMin: "3.0",
    canonicalUrl: "https://buildyourfuture.withgoogle.com/scholarships/google-lime-scholarship",
    nameHash: "google-lime-scholarship",
    eligibilityFingerprint: "disability-tech",
  },
  {
    name: "Esperanza Education Fund",
    amount: 5000,
    amountMax: 20000,
    deadline: new Date("2026-04-15"),
    applicationUrl: "https://www.esperanzafund.org/",
    source: "Esperanza",
    requiredDocs: JSON.stringify(["Transcripts", "Essay", "Tax return", "Community service log"]),
    essayPrompts: JSON.stringify(["Describe your immigrant background and community contributions."]),
    educationLevel: JSON.stringify(["HS_SENIOR"]),
    citizenshipTypes: JSON.stringify(["US_CITIZEN", "PERMANENT_RESIDENT", "F1_STUDENT", "DACA", "ASYLUM"]),
    incomeBrackets: JSON.stringify(["UNDER_15000", "15000_30000", "30000_50000"]),
    canonicalUrl: "https://www.esperanzafund.org/apply",
    nameHash: "esperanza-education-fund",
    eligibilityFingerprint: "immigrant-community",
  },
  {
    name: "Paul & Daisy Soros Fellowships",
    amount: 25000,
    amountMax: 90000,
    deadline: new Date("2026-10-27"),
    applicationUrl: "https://www.pdsorosscholars.org/",
    source: "Paul & Daisy Soros",
    requiredDocs: JSON.stringify(["Transcripts", "Essay", "References", "Immigration documentation"]),
    essayPrompts: JSON.stringify(["Describe your immigrant background and achievements."]),
    educationLevel: JSON.stringify(["UNDERGRAD_YEAR_3", "UNDERGRAD_YEAR_4", "GRAD_MASTERS", "GRAD_PHD", "GRAD_PROFESSIONAL"]),
    citizenshipTypes: JSON.stringify(["F1_STUDENT", "PERMANENT_RESIDENT", "ASYLUM", "REFUGEE", "DACA", "OTHER"]),
    gpaMin: "3.0",
    canonicalUrl: "https://www.pdsorosscholars.org/",
    nameHash: "paul-daisy-soros-fellowship",
    eligibilityFingerprint: "newamerican-immigrant",
  },
  {
    name: "Billy Graham Scholarship",
    amount: 2000,
    amountMax: 10000,
    deadline: new Date("2026-03-31"),
    applicationUrl: "https://billygraham.org/",
    source: "Billy Graham Evangelistic Association",
    requiredDocs: JSON.stringify(["Transcripts", "Pastoral reference", "Essay"]),
    essayPrompts: JSON.stringify(["Describe your faith journey and service to church."]),
    educationLevel: JSON.stringify(["HS_SENIOR", "UNDERGRAD_YEAR_1", "UNDERGRAD_YEAR_2", "UNDERGRAD_YEAR_3", "UNDERGRAD_YEAR_4"]),
    religiousAffiliation: JSON.stringify(["Christian"]),
    gpaMin: "2.5",
    canonicalUrl: "https://billygraham.org/scholarships",
    nameHash: "billy-graham-scholarship",
    eligibilityFingerprint: "christian-service",
  },
  {
    name: "AISES Scholarship",
    amount: 3000,
    amountMax: 15000,
    deadline: new Date("2026-02-01"),
    applicationUrl: "https://www.aises.org/",
    source: "AISES",
    requiredDocs: JSON.stringify(["Transcripts", "Essay", "Tribe documentation", "Recommendations"]),
    essayPrompts: JSON.stringify(["Describe your STEM interests and tribal community involvement."]),
    educationLevel: JSON.stringify(["HS_SENIOR", "UNDERGRAD_YEAR_1", "UNDERGRAD_YEAR_2", "UNDERGRAD_YEAR_3", "UNDERGRAD_YEAR_4", "GRAD_MASTERS"]),
    demographics: JSON.stringify(["AMERICAN_INDIAN", "ALASKA_NATIVE"]),
    majors: JSON.stringify(["STEM fields"]),
    gpaMin: "3.0",
    canonicalUrl: "https://www.aises.org/scholarships",
    nameHash: "aises-scholarship",
    eligibilityFingerprint: "native-stem",
  },
  {
    name: "NMF Scholarship",
    amount: 5000,
    amountMax: 25000,
    deadline: new Date("2026-04-30"),
    applicationUrl: "https://www.nmfonline.org/",
    source: "NMF",
    requiredDocs: JSON.stringify(["Transcripts", "Essay", "Recommendations", "Financial info"]),
    essayPrompts: JSON.stringify(["Describe your commitment to serving underrepresented communities."]),
    educationLevel: JSON.stringify(["GRAD_MASTERS", "GRAD_PROFESSIONAL"]),
    demographics: JSON.stringify(["AFRICAN_AMERICAN", "Hispanic/Latino", "American Indian", "Pacific Islander"]),
    majors: JSON.stringify(["Medicine", "Nursing", "Public Health", "Allied Health"]),
    gpaMin: "3.0",
    canonicalUrl: "https://www.nmfonline.org/about/scholarships/",
    nameHash: "nmf-scholarship",
    eligibilityFingerprint: "poc-healthcare",
  },
  {
    name: "Women in Defense Scholarship",
    amount: 5000,
    amountMax: 15000,
    deadline: new Date("2026-03-01"),
    applicationUrl: "https://www.womenindefense.net/",
    source: "Women in Defense",
    requiredDocs: JSON.stringify(["Transcripts", "Essay", "Recommendation letter"]),
    essayPrompts: JSON.stringify(["Describe your interest in national security and defense."]),
    educationLevel: JSON.stringify(["UNDERGRAD_YEAR_1", "UNDERGRAD_YEAR_2", "UNDERGRAD_YEAR_3", "UNDERGRAD_YEAR_4", "GRAD_MASTERS"]),
    demographics: JSON.stringify(["FEMALE"]),
    majors: JSON.stringify(["Political Science", "International Relations", "Engineering", "Computer Science", "National Security", "Business"]),
    gpaMin: "3.0",
    canonicalUrl: "https://www.womenindefense.net/scholarship",
    nameHash: "women-in-defense-scholarship",
    eligibilityFingerprint: "women-national-security",
  },
  {
    name: "Veterans United Foundation Scholarship",
    amount: 5000,
    amountMax: 20000,
    deadline: new Date("2026-02-28"),
    applicationUrl: "https://www.veteransunited.com/",
    source: "Veterans United",
    requiredDocs: JSON.stringify(["DD-214", "Transcripts", "Essay"]),
    essayPrompts: JSON.stringify(["Describe your military service and future goals."]),
    educationLevel: JSON.stringify(["UNDERGRAD_YEAR_1", "UNDERGRAD_YEAR_2", "UNDERGRAD_YEAR_3", "UNDERGRAD_YEAR_4", "GRAD_MASTERS"]),
    demographics: JSON.stringify(["VETERAN"]),
    gpaMin: "2.5",
    canonicalUrl: "https://www.veteransunited.com/foundation/scholarships/",
    nameHash: "veterans-united-scholarship",
    eligibilityFingerprint: "veteran-highered",
  },
  {
    name: "APA Minority Fellowship",
    amount: 5000,
    amountMax: 20000,
    deadline: new Date("2026-03-15"),
    applicationUrl: "https://www.apa.org/",
    source: "APA",
    requiredDocs: JSON.stringify(["Transcripts", "Research statement", "Recommendations"]),
    essayPrompts: JSON.stringify(["Describe your research interests in psychology."]),
    educationLevel: JSON.stringify(["GRAD_MASTERS", "GRAD_PHD"]),
    demographics: JSON.stringify(["AFRICAN_AMERICAN", "Hispanic/Latino", "American Indian", "Pacific Islander"]),
    majors: JSON.stringify(["Psychology", "Behavioral Sciences"]),
    gpaMin: "3.0",
    canonicalUrl: "https://www.apa.org/",
    nameHash: "apa-minority-fellowship",
    eligibilityFingerprint: "poc-psychology",
  },
  {
    name: "BNSF Foundation Scholarship",
    amount: 5000,
    amountMax: 15000,
    deadline: new Date("2026-01-15"),
    applicationUrl: "https://www.bnsf.com/",
    source: "BNSF Foundation",
    requiredDocs: JSON.stringify(["Transcripts", "Essay", "Recommendation letter"]),
    essayPrompts: JSON.stringify(["Describe your interest in rail industry careers."]),
    educationLevel: JSON.stringify(["UNDERGRAD_YEAR_1", "UNDERGRAD_YEAR_2", "UNDERGRAD_YEAR_3", "UNDERGRAD_YEAR_4"]),
    majors: JSON.stringify(["Engineering", "Business", "Supply Chain", "Transportation", "Logistics"]),
    stateResidency: JSON.stringify(["Texas", "Kansas", "Missouri", "Arkansas", "Oklahoma", "New Mexico", "North Dakota", "South Dakota", "Montana", "Wyoming", "Colorado", "California", "Oregon", "Washington"]),
    gpaMin: "3.0",
    canonicalUrl: "https://www.bnsf.com/about-bnsf/scholarships",
    nameHash: "bnsf-scholarship",
    eligibilityFingerprint: "bnsf-states-rail",
  },
  {
    name: "Foster Youth Scholarship",
    amount: 5000,
    amountMax: 10000,
    deadline: new Date("2026-04-01"),
    applicationUrl: "https://www.nfyac.org/",
    source: "NFYAC",
    requiredDocs: JSON.stringify(["Transcripts", "Essay", "Letter from caseworker", "Financial info"]),
    essayPrompts: JSON.stringify(["Describe your experience in foster care and future goals."]),
    educationLevel: JSON.stringify(["HS_SENIOR", "UNDERGRAD_YEAR_1", "UNDERGRAD_YEAR_2", "UNDERGRAD_YEAR_3", "UNDERGRAD_YEAR_4"]),
    demographics: JSON.stringify(["FOSTER_CARE"]),
    gpaMin: "2.0",
    canonicalUrl: "https://www.nfyac.org/scholarship",
    nameHash: "foster-youth-scholarship",
    eligibilityFingerprint: "foster-care",
  },
  {
    name: "Siemens Foundation Scholarship",
    amount: 10000,
    amountMax: 40000,
    deadline: new Date("2026-01-15"),
    applicationUrl: "https://www.siemens-foundation.org/",
    source: "Siemens Foundation",
    requiredDocs: JSON.stringify(["Transcripts", "Essay", "Recommendations", "FAFSA"]),
    essayPrompts: JSON.stringify(["Describe your STEM research achievements."]),
    educationLevel: JSON.stringify(["UNDERGRAD_YEAR_1", "UNDERGRAD_YEAR_2", "UNDERGRAD_YEAR_3", "UNDERGRAD_YEAR_4", "GRAD_MASTERS", "GRAD_PHD"]),
    majors: JSON.stringify(["STEM fields"]),
    gpaMin: "3.0",
    incomeBrackets: JSON.stringify(["UNDER_15000", "15000_30000", "30000_50000", "50000_75000"]),
    canonicalUrl: "https://www.siemens-foundation.org/scholarships/",
    nameHash: "siemens-foundation-scholarship",
    eligibilityFingerprint: "stem-need",
  },
  {
    name: "ABF Minority Law Scholarship",
    amount: 10000,
    amountMax: 40000,
    deadline: new Date("2026-02-28"),
    applicationUrl: "https://www.americanbar.org/",
    source: "American Bar Foundation",
    requiredDocs: JSON.stringify(["Transcripts", "LSAT", "Essay", "Recommendations"]),
    essayPrompts: JSON.stringify(["Describe your commitment to diversity in law."]),
    educationLevel: JSON.stringify(["GRAD_PROFESSIONAL"]),
    demographics: JSON.stringify(["AFRICAN_AMERICAN", "Hispanic/Latino", "American Indian", "Pacific Islander"]),
    majors: JSON.stringify(["Law", "Political Science", "Pre-Law"]),
    gpaMin: "3.0",
    canonicalUrl: "https://www.americanbarfoundation.org/",
    nameHash: "abf-minority-law-scholarship",
    eligibilityFingerprint: "poc-law",
  },
  {
    name: "Catching the Dream Scholarship",
    amount: 2500,
    amountMax: 15000,
    deadline: new Date("2026-03-15"),
    applicationUrl: "https://www.catchingthedream.org/",
    source: "Catching the Dream",
    requiredDocs: JSON.stringify(["Tribe enrollment", "Transcripts", "Essay", "Financial info"]),
    essayPrompts: JSON.stringify(["Describe your educational goals and tribal community."]),
    educationLevel: JSON.stringify(["HS_SENIOR", "UNDERGRAD_YEAR_1", "UNDERGRAD_YEAR_2", "UNDERGRAD_YEAR_3", "UNDERGRAD_YEAR_4", "GRAD_MASTERS", "GRAD_PHD"]),
    demographics: JSON.stringify(["AMERICAN_INDIAN", "ALASKA_NATIVE"]),
    gpaMin: "2.5",
    canonicalUrl: "https://www.catchingthedream.org/",
    nameHash: "catching-the-dream-scholarship",
    eligibilityFingerprint: "native-student-aid",
  },
  {
    name: "Military Spouse Scholarship",
    amount: 2500,
    amountMax: 5000,
    deadline: new Date("2026-12-31"),
    applicationUrl: "https://www.military.com/",
    source: "NMFA",
    requiredDocs: JSON.stringify(["Marriage certificate", "Sponsor statement", "Transcripts", "Essay"]),
    essayPrompts: JSON.stringify(["Describe your journey as a military spouse pursuing education."]),
    educationLevel: JSON.stringify(["UNDERGRAD_YEAR_1", "UNDERGRAD_YEAR_2", "UNDERGRAD_YEAR_3", "UNDERGRAD_YEAR_4", "GRAD_MASTERS", "NON_DEGREE"]),
    militaryAffiliation: JSON.stringify(["Military spouse"]),
    gpaMin: "2.5",
    canonicalUrl: "https://www.military.com/family-and-military-veterans/scholarships-for-military-families.html",
    nameHash: "military-spouse-scholarship",
    eligibilityFingerprint: "military-spouse",
  },
  {
    name: "Google Women Techmakers Scholarship",
    amount: 10000,
    amountMax: 20000,
    deadline: new Date("2026-03-15"),
    applicationUrl: "https://buildyourfuture.withgoogle.com/",
    source: "Google",
    requiredDocs: JSON.stringify(["Resume", "Transcripts", "Essay"]),
    essayPrompts: JSON.stringify(["Describe your tech contributions and future goals."]),
    educationLevel: JSON.stringify(["UNDERGRAD_YEAR_1", "UNDERGRAD_YEAR_2", "UNDERGRAD_YEAR_3", "UNDERGRAD_YEAR_4", "GRAD_MASTERS"]),
    demographics: JSON.stringify(["FEMALE"]),
    majors: JSON.stringify(["Computer Science", "Engineering", "Technology", "Business"]),
    gpaMin: "3.0",
    canonicalUrl: "https://buildyourfuture.withgoogle.com/scholarships/google-women-techmakers",
    nameHash: "google-women-techmakers",
    eligibilityFingerprint: "women-tech",
  },
  {
    name: "NSBE Scholarship",
    amount: 5000,
    amountMax: 20000,
    deadline: new Date("2026-01-31"),
    applicationUrl: "https://www.nsbe.org/",
    source: "NSBE",
    requiredDocs: JSON.stringify(["NSBE membership", "Transcripts", "Essay", "Recommendations"]),
    essayPrompts: JSON.stringify(["Describe your engineering achievements and community involvement."]),
    educationLevel: JSON.stringify(["HS_SENIOR", "UNDERGRAD_YEAR_1", "UNDERGRAD_YEAR_2", "UNDERGRAD_YEAR_3", "UNDERGRAD_YEAR_4", "GRAD_MASTERS", "GRAD_PHD"]),
    demographics: JSON.stringify(["AFRICAN_AMERICAN"]),
    majors: JSON.stringify(["Engineering", "Computer Science", "STEM"]),
    gpaMin: "3.0",
    canonicalUrl: "https://www.nsbe.org/competitions/scholarships",
    nameHash: "nsbe-scholarship",
    eligibilityFingerprint: "africanamerican-engineering",
  },
  {
    name: "LGBTQ Law Scholarship",
    amount: 10000,
    amountMax: 25000,
    deadline: new Date("2026-02-15"),
    applicationUrl: "https://www.sullcrom.com/",
    source: "Sullivan & Cromwell LLP",
    requiredDocs: JSON.stringify(["Transcripts", "Essay", "Recommendation letters"]),
    essayPrompts: JSON.stringify(["Describe your commitment to diversity and inclusion in law."]),
    educationLevel: JSON.stringify(["GRAD_PROFESSIONAL", "GRAD_MASTERS"]),
    demographics: JSON.stringify(["LGBTQ"]),
    majors: JSON.stringify(["Law", "Business", "Political Science"]),
    gpaMin: "3.0",
    canonicalUrl: "https://www.sullcrom.com/careers/scholarships",
    nameHash: "lgbtq-law-scholarship",
    eligibilityFingerprint: "lgbtq-law",
  },
];

async function main() {
  console.log("Seeding scholarships...");

  for (const scholarship of scholarships) {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const data = scholarship as any;

    // Parse JSON string fields that are stored as arrays in Prisma
    const parseJson = (val: unknown): unknown => {
      if (typeof val === "string") {
        try { return JSON.parse(val); }
        catch { return val; }
      }
      return val;
    };

    const parsedData = {
      ...data,
      requiredDocs: parseJson(data.requiredDocs),
      essayPrompts: parseJson(data.essayPrompts),
      educationLevel: parseJson(data.educationLevel),
      citizenshipTypes: parseJson(data.citizenshipTypes),
      demographics: parseJson(data.demographics),
      incomeBrackets: parseJson(data.incomeBrackets),
      ethnicity: parseJson(data.ethnicity),
      stateResidency: parseJson(data.stateResidency),
      majors: parseJson(data.majors),
      sopTags: parseJson(data.sopTags),
      militaryAffiliation: parseJson(data.militaryAffiliation),
      religiousAffiliation: parseJson(data.religiousAffiliation),
    };

    await prisma.scholarship.upsert({
      where: { canonicalUrl: parsedData.canonicalUrl },
      update: {
        name: parsedData.name,
        amount: parsedData.amount,
        amountMax: parsedData.amountMax,
        deadline: parsedData.deadline,
        applicationUrl: parsedData.applicationUrl,
        source: parsedData.source,
        requiredDocs: parsedData.requiredDocs,
        essayPrompts: parsedData.essayPrompts,
        educationLevel: parsedData.educationLevel,
        citizenshipTypes: parsedData.citizenshipTypes,
        gpaMin: parsedData.gpaMin ?? null,
        demographics: parsedData.demographics,
        incomeBrackets: parsedData.incomeBrackets,
        ethnicity: parsedData.ethnicity,
        stateResidency: parsedData.stateResidency,
        majors: parsedData.majors,
        canonicalUrl: parsedData.canonicalUrl,
        nameHash: parsedData.nameHash,
        eligibilityFingerprint: parsedData.eligibilityFingerprint,
        communityServiceRequired: parsedData.communityServiceRequired ?? false,
        disabilityStatusRequired: parsedData.disabilityStatusRequired ?? false,
        religiousAffiliation: parsedData.religiousAffiliation,
        militaryAffiliation: parsedData.militaryAffiliation,
        homeCountry: parsedData.homeCountry,
        englishProficiency: parsedData.englishProficiency ?? false,
        sopTags: parsedData.sopTags,
        isSponsored: parsedData.isSponsored ?? false,
        isArchived: false,
      },
      create: {
        name: parsedData.name,
        amount: parsedData.amount,
        amountMax: parsedData.amountMax,
        deadline: parsedData.deadline,
        applicationUrl: parsedData.applicationUrl,
        source: parsedData.source,
        requiredDocs: parsedData.requiredDocs,
        essayPrompts: parsedData.essayPrompts,
        educationLevel: parsedData.educationLevel,
        citizenshipTypes: parsedData.citizenshipTypes,
        gpaMin: parsedData.gpaMin ?? null,
        demographics: parsedData.demographics,
        incomeBrackets: parsedData.incomeBrackets,
        ethnicity: parsedData.ethnicity,
        stateResidency: parsedData.stateResidency,
        majors: parsedData.majors,
        canonicalUrl: parsedData.canonicalUrl,
        nameHash: parsedData.nameHash,
        eligibilityFingerprint: parsedData.eligibilityFingerprint,
        communityServiceRequired: parsedData.communityServiceRequired ?? false,
        disabilityStatusRequired: parsedData.disabilityStatusRequired ?? false,
        religiousAffiliation: parsedData.religiousAffiliation,
        militaryAffiliation: parsedData.militaryAffiliation,
        homeCountry: parsedData.homeCountry,
        englishProficiency: parsedData.englishProficiency ?? false,
        sopTags: parsedData.sopTags,
        isSponsored: parsedData.isSponsored ?? false,
        isArchived: false,
      },
    });
  }

  console.log(`Seeded ${scholarships.length} scholarships`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
